CREATE TABLE IF NOT EXISTS categoria_recurso (
    idCategoria INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE, descripcion TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS usuario_sistema (
    idUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombreUsuario VARCHAR(80) NOT NULL UNIQUE,
    contrasenaHash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fechaRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS persona (
    idPersona INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombres VARCHAR(120) NOT NULL, apellidos VARCHAR(120) NOT NULL,
    documentoIdentidad VARCHAR(20) NOT NULL UNIQUE,
    correo VARCHAR(160) NOT NULL, telefono VARCHAR(25) NOT NULL,
    tipo ENUM('ESTUDIANTE','DOCENTE','ADMINISTRATIVO') NOT NULL,
    estado ENUM('ACTIVA','INACTIVA','EGRESADA','RETIRADA','SUSPENDIDA') NOT NULL DEFAULT 'ACTIVA',
    fechaRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS estudiante (
    idPersona INT NOT NULL PRIMARY KEY,
    codigoEstudiante VARCHAR(120) NOT NULL UNIQUE,
    matricula VARCHAR(120) NOT NULL, ciclo INT NOT NULL,
    semestreAcademico VARCHAR(120) NOT NULL, estadoMatricula VARCHAR(120) NOT NULL,
    FOREIGN KEY (idPersona) REFERENCES persona(idPersona)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS docente (
    idPersona INT NOT NULL PRIMARY KEY,
    codigoDocente VARCHAR(120) NOT NULL UNIQUE,
    departamentoAcademico VARCHAR(120) NOT NULL, facultad VARCHAR(120) NOT NULL,
    escuelaProfesional VARCHAR(120) NOT NULL,
    FOREIGN KEY (idPersona) REFERENCES persona(idPersona)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS administrativo (
    idPersona INT NOT NULL PRIMARY KEY,
    codigoEmpleado VARCHAR(120) NOT NULL UNIQUE, area VARCHAR(120) NOT NULL,
    FOREIGN KEY (idPersona) REFERENCES persona(idPersona)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS recurso (
    idRecurso INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    tipo ENUM('LIBRO','LAPTOP','PROYECTOR','CARGADOR','MOUSE','TABLET','OTRO') NOT NULL,
    marca VARCHAR(80) NOT NULL, modelo VARCHAR(80) NOT NULL, descripcion TEXT NOT NULL,
    idCategoriaRef INT NOT NULL,
    FOREIGN KEY (idCategoriaRef) REFERENCES categoria_recurso(idCategoria)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS bien_material (
    idBien INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idRecursoRef INT NOT NULL,
    codigoInventario VARCHAR(40) NOT NULL UNIQUE,
    numeroSerie VARCHAR(100) NOT NULL, fechaAdquisicion DATE NOT NULL,
    estado ENUM('DISPONIBLE','PRESTADO','RESERVADO','DANADO','MANTENIMIENTO','PERDIDO') NOT NULL,
    ubicacion VARCHAR(120) NOT NULL,
    FOREIGN KEY (idRecursoRef) REFERENCES recurso(idRecurso)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
